<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>IT Support Ticket Report</title>
    <style>
        /* ===== BASE ===== */
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 9.5px;
            color: #2c3e50;
            margin: 130px 25px 60px 25px; /* Lebih longgar agar header/footer tidak bentrok */
            line-height: 1.45;
        }

        h1, h2, h3, h4, p { margin: 0; padding: 0; }

        /* ===== HEADER ===== */
        header {
            position: fixed;
            top: 20px;
            left: 25px;
            right: 25px;
            display: flex;
            align-items: flex-start;
            padding-bottom: 6px;
            height: 85px; /* tinggi tetap agar konten tidak nabrak */
        }

        header img {
            width: 52px;
            height: auto;
            margin-right: 14px;
        }
.header-line {
    border-top: 2px solid #003366;
    margin-top: 15px; /* atur sesuai tinggi header */
    margin-bottom: none;
}

        .header-info h2 {
            font-size: 14.5px;
            color: #003366;
            margin-bottom: 3px;
            letter-spacing: 0.4px;
        }

        .header-info p {
            font-size: 9.5px;
            color: #444;
            margin-bottom: 3px;
        }

        /* ===== FOOTER ===== */
        footer {
            position: fixed;
            bottom: 10px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 9px;
            color: #666;
            border-top: 1px solid #ccc;
            padding-top: 3px;
        }

        /* ===== MAIN ===== */
        main {
            margin-top: 10px;
        }

        .report-summary {
            background: #f8f9fa;
            padding: 8px 12px;
            border-left: 4px solid #003366;
            font-size: 9.3px;
            color: #333;
            margin-bottom: 18px;
        }

        .report-summary strong { color: #003366; }

        h3.section-title {
            color: #003366;
            font-size: 11.5px;
            letter-spacing: 0.3px;
            margin-bottom: 8px;
            border-bottom: 1.5px solid #003366;
            padding-bottom: 3px;
            font-weight: bold;
        }

        /* ===== TABLE ===== */
        table {
            width: 100%;
            border-collapse: collapse;
            border-spacing: 0;
            table-layout: fixed;
        }

        thead {
            background: #003366;
            color: white;
        }

        th, td {
            padding: 6px 7px;
            border-bottom: 1px solid #e1e7f0;
            text-align: left;
            vertical-align: top;
            word-wrap: break-word;
        }

        th {
            text-transform: uppercase;
            letter-spacing: 0.25px;
            font-size: 8.6px;
        }

        td {
            font-size: 8.7px;
            line-height: 1.3;
        }

        tbody tr:nth-child(even) { background: #f4f7fb; }

        /* ===== COLUMN WIDTHS (lebih proporsional) ===== */
        th:nth-child(1), td:nth-child(1) { width: 7%; }
        th:nth-child(2), td:nth-child(2) { width: 26%; }
        th:nth-child(3), td:nth-child(3) { width: 13%; }
        th:nth-child(4), td:nth-child(4) { width: 12%; }
        th:nth-child(5), td:nth-child(5) { width: 13%; }
        th:nth-child(6), td:nth-child(6) { width: 9%; text-align: center; }
        th:nth-child(7), td:nth-child(7),
        th:nth-child(8), td:nth-child(8) { width: 10%; text-align: center; }

        /* ===== BADGES ===== */
        .badge {
            display: inline-block;
            padding: 2px 5px;
            border-radius: 3px;
            font-size: 8px;
            font-weight: bold;
            color: #fff;
            text-transform: capitalize;
            white-space: nowrap;
        }

        .waiting { background-color: #95a5a6; }
        .in_progress { background-color: #3498db; }
        .pending { background-color: #f39c12; }
        .resolved { background-color: #27ae60; }
        .closed { background-color: #7f8c8d; }

        /* ===== META ===== */
        .meta-line {
            font-size: 8.5px;
            color: #777;
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>

<header>
    <img src="{{ public_path('assets/image/logo-ktu.jpg') }}" alt="Company Logo">
    <div class="header-info">
        <h2>PT KTU Shipyard</h2>
        <p>IT Support Department</p>
        <p><strong>Monthly Ticket Report</strong> — Period: {{ now()->format('F Y') }}</p>
    </div>
</header>

<div class="header-line"></div>

<footer>
    Generated by IT Support System — {{ now()->format('d M Y') }} | Page <span class="pagenum"></span>
</footer>

<main>
    <div class="report-summary">
        This document summarizes all IT support tickets recorded during
        <strong>{{ now()->format('F Y') }}</strong>. It includes issue categories,
        assigned users, departments, and current statuses.
    </div>

    <h3 class="section-title">Ticket List</h3>

    <table>
        <thead>
            <tr>
                <th>ID Ticket</th>
                <th>Description</th>
                <th>User</th>
                <th>Department</th>
                <th>Category</th>
                <th>Status</th>
                <th>Created</th>
                <th>Updated</th>
            </tr>
        </thead>
        <tbody>
            @foreach($tickets as $ticket)
                <tr>
                    <td>#TK{{ str_pad($ticket->id, 3, '0', STR_PAD_LEFT) }}</td>
                    <td>{{ $ticket->description ?? 'No description provided' }}</td>
                    <td>{{ $ticket->user->name ?? 'N/A' }}</td>
                    <td>{{ $ticket->user->department->name ?? $ticket->user->department ?? 'N/A' }}</td>
                    <td>{{ $ticket->category->name ?? 'N/A' }}</td>
                    <td>
                        <span class="badge {{ strtolower(str_replace(' ', '_', $ticket->status)) }}">
                            {{ ucfirst(str_replace('_', ' ', $ticket->status)) }}
                        </span>
                    </td>
                    <td>{{ $ticket->created_at->format('Y-m-d') }}</td>
                    <td>{{ $ticket->updated_at->format('Y-m-d') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="meta-line">
        Confidential Report — For Internal Use Only
    </div>
</main>

<script type="text/php">
    if (isset($pdf)) {
        $pdf->page_script('
            $font = $fontMetrics->get_font("DejaVu Sans", "normal");
            $size = 8.5;
            $pageText = "Page " . $PAGE_NUM . " of " . $PAGE_COUNT;
            $y = 810;
            $x = 520;
            $pdf->text($x, $y, $pageText, $font, $size);
        ');
    }
</script>

</body>
</html>
